CREATE TABLE IF NOT EXISTS News_Categories (
	id SERIAL PRIMARY KEY,
 	news_id INT NOT NULL,
	categories_id INT NOT NULL,
	FOREIGN KEY(news_id) REFERENCES News (id) ON DELETE CASCADE ON UPDATE CASCADE
)